### ISSUE TITLE
can i record background music?

### ISSUE THREAD

**Issue by davut5** [nixzhu/AudioBot#1]
i want to record my voice and playing background music and merge them. can i make?

**Comment by nixzhu** [comment]
Maybe one day, but not now.

**Comment by davut5** [comment]
WHY?

**Comment by nixzhu** [comment]
Version 0.2 supports mix background music when recoding.

**Comment by davut5** [comment]
thank you for your help. and share this for us.
yes it is working but with headphone not working.  without headphone plugged-in working perfect.. :(

**Comment by davut5** [comment]
will you make? or Maybe one day, but not now.  :)

**Comment by davut5** [comment]
i am waiting your help. please show me a way.

**Comment by davut5** [comment]
@nixzhu  can u help for this please.. :(
